def country_name():
    return {
        "阿富汗": "Afghanistan",
        "阿尔巴尼亚": "Albania",
        "阿尔及利亚": "Algeria",
        "安道尔": "Andorra",
        "安哥拉": "Angola",
        "安提瓜和巴布达": "Antigua and Barbuda",
        "阿根廷": "Argentina",
        "亚美尼亚": "Armenia",
        "澳大利亚": "Australia",
        "Australia": "Australia",
        "奥地利": "Austria",
        "阿塞拜疆": "Azerbaijan",
        "巴哈马": "Bahamas",
        "巴林": "Bahrain",
        "孟加拉国": "Bangladesh",
        "Bangladesh": "Bangladesh",
        "巴巴多斯": "Barbados",
        "白俄罗斯": "Belarus",
        "Belarus": "Belarus",
        "比利时": "Belgium",
        "Belgium": "Belgium",
        "伯利兹": "Belize",
        "贝宁": "Benin",
        "Benin": "Benin",
        "不丹": "Bhutan",
        "玻利维亚": "Bolivia",
        "波斯尼亚和黑塞哥维那": "Bosnia and Herzegovina",
        "博茨瓦纳": "Botswana",
        "巴西": "Brazil",
        "保加利亚": "Bulgaria",
        "布基纳法索": "Burkina Faso",
        "布隆迪": "Burundi",
        "柬埔寨": "Cambodia",
        "喀麦隆": "Cameroon",
        "Cameroon": "Cameroon",
        "加拿大": "Canada",
        "QuebecCanada": "Canada",
        "Canada": "Canada",
        "佛得角": "Cape Verde",
        "中非共和国": "Central African Republic",
        "乍得": "Chad",
        "智利": "Chile",
        "中国台湾": "China",
        "台湾": "China",
        "中国香港": "China",
        "香港": "China",
        "中国澳门": "China",
        "中国大陆": "China",
        "大陆": "China",
        "中国大": "China",
        "中国": "China",
        "台灣": "China",
        "哥伦比亚": "Colombia",
        "科摩罗": "Comoros",
        "刚果（布）": "Congo (Brazzaville)",
        "刚果（金）": "Congo (Kinshasa)",
        "哥斯达黎加": "Costa Rica",
        "克罗地亚": "Croatia",
        "克罗地亚共和国": "Croatia",
        "古巴": "Cuba",
        "塞浦路斯": "Cyprus",
        "捷克": "Czech Republic",
        "捷克斯洛伐克": "Czech Republic",
        "丹麦": "Denmark",
        "Denmark": "Denmark",
        "吉布提": "Djibouti",
        "多米尼加共和国": "Dominican Republic",
        "东帝汶": "East Timor",
        "厄瓜多尔": "Ecuador",
        "Ecuador": "Ecuador",
        "埃及": "Egypt",
        "萨尔瓦多": "El Salvador",
        "赤道几内亚": "Equatorial Guinea",
        "厄立特里亚": "Eritrea",
        "爱沙尼亚": "Estonia",
        "埃塞俄比亚": "Ethiopia",
        "斐": "Fiji",
        "芬兰": "Finland",
        "Finland": "Finland",
        "法国": "France",
        "France": "France",
        "加蓬": "Gabon",
        "冈比亚": "Gambia",
        "格鲁吉亚": "Georgia",
        "德国": "Germany",
        "东德": "Germany",
        "西德": "Germany",
        "原西德": "Germany",
        "Germany": "Germany",
        "WestGermany": "Germany",
        "加纳": "Ghana",
        "希腊": "Greece",
        "格林纳达": "Grenada",
        "危地马拉": "Guatemala",
        "几内亚": "Guinea",
        "几内亚比绍": "Guinea-Bissau",
        "圭亚那": "Guyana",
        "海地": "Haiti",
        "洪都拉斯": "Honduras",
        "匈牙利": "Hungary",
        "Hungary": "Hungary",
        "冰岛": "Iceland",
        "Iceland": "Iceland",
        "印度": "India",
        "印度尼西亚": "Indonesia",
        "伊朗": "Iran",
        "伊拉克": "Iraq",
        "爱尔兰": "Ireland",
        "Ireland": "Ireland",
        "以色列": "Israel",
        "意大利": "Italy",
        "Italian": "Italy",
        "Italy": "Italy",
        "牙买加": "Jamaica",
        "Jamaica": "Jamaica",
        "日本": "Japan",
        "Japan": "Japan",
        "约旦": "Jordan",
        "哈萨克斯坦": "Kazakhstan",
        "Kazakhstan": "Kazakhstan",
        "肯尼亚": "Kenya",
        "基里巴斯": "Kiribati",
        "朝鲜": "Korea, North",
        "韩国": "Korea, South",
        "科威特": "Kuwait",
        "吉尔吉斯斯坦": "Kyrgyzstan",
        "Kyrgyzstan": "Kyrgyzstan",
        "老挝": "Laos",
        "拉脱维亚": "Latvia",
        "黎巴嫩": "Lebanon",
        "莱索托": "Lesotho",
        "利比里亚": "Liberia",
        "利比亚": "Libya",
        "列支敦士登": "Liechtenstein",
        "立陶宛": "Lithuania",
        "卢森堡": "Luxembourg",
        "马其顿": "Macedonia",
        "马达加斯加": "Madagascar",
        "马拉维": "Malawi",
        "马来西亚": "Malaysia",
        "马尔代夫": "Maldives",
        "马里": "Mali",
        "Mali": "Mali",
        "马耳他": "Malta",
        "Malta": "Malta",
        "马绍尔群岛": "Marshall Islands",
        "毛里塔尼亚": "Mauritania",
        "毛里求斯": "Mauritius",
        "墨西哥": "Mexico",
        "Mexico": "Mexico",
        "密克罗尼西亚联邦": "Micronesia",
        "摩尔多瓦": "Moldova",
        "摩纳哥": "Monaco",
        "蒙古": "Mongolia",
        "黑山": "Montenegro",
        "摩洛哥": "Morocco",
        "莫桑比克": "Mozambique",
        "缅甸": "Myanmar",
        "纳米比亚": "Namibia",
        "瑙鲁": "Nauru",
        "尼泊尔": "Nepal",
        "荷兰": "Netherlands",
        "Holland": "Netherlands",
        "Netherlands": "Netherlands",
        "新西兰": "New Zealand",
        "NewZealand": "New Zealand",
        "尼加拉瓜": "Nicaragua",
        "尼日尔": "Niger",
        "尼日利亚": "Nigeria",
        "挪威": "Norway",
        "阿曼": "Oman",
        "巴基斯坦": "Pakistan",
        "帕劳": "Palau",
        "巴勒斯坦": "Palestinian State",
        "巴拿马": "Panama",
        "巴布亚新几内亚": "Papua New Guinea",
        "巴拉圭": "Paraguay",
        "秘鲁": "Peru",
        "菲律宾": "Philippines",
        "波兰": "Poland",
        "Poland": "Poland",
        "葡萄牙": "Portugal",
        "卡塔尔": "Qatar",
        "罗马尼亚": "Romania",
        "俄罗斯": "Russia",
        "苏联": "Russia",
        "Russia": "Russia",
        "Russian": "Russia",
        "SovietUnion": "Russia",
        "阿鲁巴": "Aruba",
        "Aruba": "Aruba",
        "波多黎各": "Puerto Rico",
        "卢旺达": "Rwanda",
        "圣基茨和尼维斯": "Saint Kitts and Nevis",
        "圣卢西亚": "Saint Lucia",
        "圣文森特和格林纳丁斯": "Saint Vincent and the Grenadines",
        "萨摩亚": "Samoa",
        "圣马力诺": "San Marino",
        "圣多美和普林西比": "Sao Tome and Principe",
        "沙特阿拉伯": "Saudi Arabia",
        "塞内加尔": "Senegal",
        "Senegal": "Senegal",
        "塞尔维亚": "Serbia",
        "塞舌尔": "Seychelles",
        "塞拉利昂": "Sierra Leone",
        "新加坡": "Singapore",
        "Singapore": "Singapore",
        "斯洛伐克": "Slovakia",
        "斯洛文尼亚": "Slovenia",
        "所罗门群岛": "Solomon Islands",
        "索马里": "Somalia",
        "南非": "South Africa",
        "南苏丹": "South Sudan",
        "西班牙": "Spain",
        "Spain": "Spain",
        "斯里兰卡": "Sri Lanka",
        "苏丹": "Sudan",
        "苏里南": "Suriname",
        "斯威士兰": "Swaziland",
        "瑞典": "Sweden",
        "瑞士": "Switzerland",
        "叙利亚": "Syria",
        "塔吉克斯坦": "Tajikistan",
        "坦桑尼亚": "Tanzania",
        "泰国": "Thailand",
        "泰國": "Thailand",
        "多哥": "Togo",
        "汤加": "Tonga",
        "特立尼达和多巴哥": "Trinidad and Tobago",
        "突尼斯": "Tunisia",
        "土耳其": "Turkey",
        "土库曼斯坦": "Turkmenistan",
        "图瓦卢": "Tuvalu",
        "乌干达": "Uganda",
        "乌克兰": "Ukraine",
        "阿联酋": "United Arab Emirates",
        "UnitedArabEmirates": "United Arab Emirates",
        "英国": "United Kingdom",
        "UK": "United Kingdom",
        "英国UK": "United Kingdom",
        "BBC": "United Kingdom",
        "英国BBC": "United Kingdom",
        "美国": "United States",
        "UnitedStates": "United States",
        "美國": "United States",
        "USA": "United States",
        "US": "United States",
        "U.S.A": "United States",
        "乌拉圭": "Uruguay",
        "乌兹别克斯坦": "Uzbekistan",
        "瓦努阿图": "Vanuatu",
        "梵蒂冈": "Vatican City",
        "委内瑞拉": "Venezuela",
        "越南": "Vietnam",
        "NorthVietnam": "Vietnam",
        "也门": "Yemen",
        "赞比亚": "Zambia",
        "津巴布韦": "Zimbabwe",
        '多米尼加': "The Dominican Republic",
        "波黑": 'Bosnia and Herzegovina',
        "格陵兰": "Greenland"
    }

